core/urls.py
from django.urls import path

from . import views


app_name = "content"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakt', views.ContactView.as_view(), name='contact'),
    path('artikel', views.ArticlesView.as_view(), name='articles_all'),
    # path('dsgvo', views.ArticlesView.as_view(), name='dsgvo'),
    path('artikel/tag/<slug:tag>/', views.ArticlesView.as_view(), name='articles'),
    path('artikel/<slug:slug>', views.ArticleView.as_view(), name='article'),
    path('leistung/<slug:slug>', views.ServiceView.as_view(), name='service'),
    path('ueber-uns/', views.AboutView.as_view(), name='about'),
    path('error/', views.ErrorView.as_view(), name='error'),
    path('datenschutz/', views.DataProtectionView.as_view(), name='data_protection'),
    path('impressum/', views.ImprintView.as_view(), name='imprint'),
    # user
    path('benutzer/', views.SettingsView.as_view(), name='users_index'),
    path('benutzer/login', views.SignInView.as_view(), name='signin'),
    path('benutzer/logout', views.SignOutView.as_view(), name='signout'),
    path('benutzer/einstellungen', views.SettingsView.as_view(), name='settings'),
    path('benutzer/passwort-aendern', views.CustomPasswordChangeView.as_view(), name='password_change'),
]

francopioli/apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    # views
    path('', views.SettingsView.as_view(), name='index'),
    path('login', views.SignInView.as_view(), name='signin'),
    path('logout', views.SignOutView.as_view(), name='signout'),
    path('einstellungen', views.SettingsView.as_view(), name='settings'),
    path('passwort-aendern', views.CustomPasswordChangeView.as_view(), name='password_change'),
]

core/models/users.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

francopioli/apps/users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

francopioli/apps/users/forms.py
from django import forms

francopioli/apps/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from django.urls import reverse_lazy


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'password.html'
    success_url = reverse_lazy('users:signin')


class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    pass


class SignInView(LoginView):
    template_name = 'login.html'
    redirect_field_name = 'next'


class SettingsView(LoginRequiredMixin, TemplateView):
    template_name = 'settings.html'


class SignOutView(LogoutView):
    next_page = '/'

francopioli/apps/users/templates/base.html
{% load static %}
{% load svg %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
</head>
<body>
<div class="bg-primary w-100 p-1"></div>
<div class="py-2 px-2 bg-light">
    {% url 'users:settings' as settings_url %}
    {% include 'content/symbols/link.html' with href=settings_url text='Benutzer-Einstellungen' %}
</div>
{% block body %}

{% endblock %}
</body>
</html>

francopioli/apps/users/templates/settings.html
{% extends 'base.html' %}

{% block body %}
    <section class="">
        <div class="container d-flex flex-column">
            <div class="row align-items-center justify-content-center no-gutters min-vh-100">
                <div class="col-12 col-md-6 col-lg-6 py-8 py-md-11">
                    <h1 class="mb-4 font-weight-bold text-center">
                        Hallo {{ user.first_name }} {{ user.last_name }}
                    </h1>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'content:index' %}">Zur Startseite</a></li>
                        <li><a href="{% url 'users:password_change' %}">Passwort ändern</a></li>
                        <li><a href="{% url 'users:signout' %}">Abmelden</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
{% endblock %}