core/urls.py
from django.urls import path

from . import views


app_name = "content"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakt', views.ContactView.as_view(), name='contact'),
    path('artikel', views.ArticlesView.as_view(), name='articles_all'),
    # path('dsgvo', views.ArticlesView.as_view(), name='dsgvo'),
    path('artikel/tag/<slug:tag>/', views.ArticlesView.as_view(), name='articles'),
    path('artikel/<slug:slug>', views.ArticleView.as_view(), name='article'),
    path('leistung/<slug:slug>', views.ServiceView.as_view(), name='service'),
    path('ueber-uns/', views.AboutView.as_view(), name='about'),
    path('error/', views.ErrorView.as_view(), name='error'),
    path('datenschutz/', views.DataProtectionView.as_view(), name='data_protection'),
    path('impressum/', views.ImprintView.as_view(), name='imprint'),
    # user
    path('benutzer/', views.SettingsView.as_view(), name='users_index'),
    path('benutzer/login', views.SignInView.as_view(), name='signin'),
    path('benutzer/logout', views.SignOutView.as_view(), name='signout'),
    path('benutzer/einstellungen', views.SettingsView.as_view(), name='settings'),
    path('benutzer/passwort-aendern', views.CustomPasswordChangeView.as_view(), name='password_change'),
]

francopioli/apps/content/urls.py
from django.urls import path

from . import views


app_name = "content"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakt', views.ContactView.as_view(), name='contact'),
    path('artikel', views.ArticlesView.as_view(), name='articles'),
    path('artikel/tag/<slug:tag>/', views.ArticlesView.as_view(), name='articles_tag'),
    path('artikel/<slug:slug>', views.ArticleView.as_view(), name='article'),
    path('leistung/<slug:slug>', views.ServiceView.as_view(), name='service'),
    path('ueber-uns/', views.AboutView.as_view(), name='about'),
    path('error/', views.ErrorView.as_view(), name='error'),
    path('datenschutz/', views.DataProtectionView.as_view(), name='data_protection'),
    path('impressum/', views.ImprintView.as_view(), name='imprint'),
]

francopioli/apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    # views
    path('', views.SettingsView.as_view(), name='index'),
    path('login', views.SignInView.as_view(), name='signin'),
    path('logout', views.SignOutView.as_view(), name='signout'),
    path('einstellungen', views.SettingsView.as_view(), name='settings'),
    path('passwort-aendern', views.CustomPasswordChangeView.as_view(), name='password_change'),
]

core/models/content.py
from ckeditor_uploader import fields
from django.db import models


class Experience(models.Model):
    time = models.TextField('Zeit')
    text = models.TextField('Erfahrung')

    class Meta:
        verbose_name_plural = 'Erfahrungen'
        verbose_name = 'Erfahrung'
        ordering = ['time']

    def __str__(self):
        return self.time


class Education(models.Model):
    time = models.TextField('Zeit')
    text = models.TextField('Bildung')

    class Meta:
        verbose_name_plural = 'Bildungen'
        verbose_name = 'Bildung'
        ordering = ['time']

    def __str__(self):
        return self.time


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name


class Article(models.Model):
    # auto
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # private
    is_account_required = models.BooleanField('Nur für eingeloggte Benutzer sichtbar', default=False)
    # public
    author = models.CharField('Autor', max_length=200)
    title = models.CharField('Titel', max_length=200)
    slug = models.SlugField('Slug', help_text='Der Name klein geschrieben und ohne Leerzeichen oder Sonderzeichen.',
                            unique=True)
    date = models.DateField('Datum')
    tags = models.ManyToManyField(Tag)
    description = models.TextField('Beschreibung')
    image = models.ImageField('Bild', upload_to='article-images/')
    content = fields.RichTextUploadingField('Inhalt')

    class Meta:
        verbose_name = 'Artikel'
        verbose_name_plural = 'Artikel'

    def __str__(self):
        return '{}: {}'.format(self.date.strftime('%d.%m.%Y'), self.title)


class Service(models.Model):
    name = models.CharField('Name', max_length=200)
    slug = models.SlugField('Slug', help_text='Der Name klein geschrieben und ohne Leerzeichen oder Sonderzeichen.',
                            unique=True)
    content = fields.RichTextUploadingField('Inhalt')

    class Meta:
        verbose_name = 'Leistung'
        verbose_name_plural = 'Leistungen'

    def __str__(self):
        return self.name

francopioli/apps/content/models.py
from django.db import models

from martor.models import MartorField


class Experience(models.Model):
    time = models.TextField()
    text = MartorField()

    class Meta:
        verbose_name_plural = 'Erfahrungen'
        verbose_name = 'Erfahrung'
        ordering = ['time']

    def __str__(self):
        return self.time


class Education(models.Model):
    time = models.TextField()
    text = MartorField()

    class Meta:
        verbose_name_plural = 'Bildungen'
        verbose_name = 'Bildung'
        ordering = ['time']

    def __str__(self):
        return self.time


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name


class Article(models.Model):
    # auto
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # private
    is_account_required = models.BooleanField(default=False)
    # public
    author = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    date = models.DateField()
    tags = models.ManyToManyField(Tag)
    description = models.TextField()
    image = models.ImageField(upload_to='article-images/')
    content = MartorField()

    class Meta:
        verbose_name = 'Artikel'
        verbose_name_plural = 'Artikel'

    def __str__(self):
        return '{}: {}'.format(self.date.strftime('%d.%m.%Y'), self.title)


class Service(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    content = MartorField()

    class Meta:
        verbose_name = 'Leistung'
        verbose_name_plural = 'Leistungen'

    def __str__(self):
        return self.name

francopioli/apps/content/forms.py
from django import forms

from .models import Article

from martor.widgets import AdminMartorWidget


class ArticleForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
                           input_formats=["%Y-%m-%d"], label="Date")
    content = forms.CharField(widget=AdminMartorWidget)

    class Meta:
        model = Article
        fields = '__all__'


class ContactForm(forms.Form):
    vorname = forms.CharField()
    nachname = forms.CharField()
    email = forms.EmailField()
    nachricht = forms.CharField()

    def clean_nachricht(self):
        message = self.cleaned_data['nachricht']
        if 'http://' in message or 'https://' in message or 'usd' in message.lower():
            raise forms.ValidationError('In der Nachricht sind keine Links erlaubt.')
        return message

francopioli/apps/content/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import TemplateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import FormView
from django.core.mail import EmailMessage
from django.shortcuts import render

from apps.core.models import TextBlock
from apps.core.views import WebsiteContextMixin
from .models import Experience
from .models import Education
from .models import Article
from .models import Service
from .models import Tag
from .forms import ContactForm


class GeneralContextMixin(WebsiteContextMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        context['textblocks'] = TextBlock.get_dict()
        return context


class IndexView(GeneralContextMixin, TemplateView):
    template_name = 'content/index.html'


class ContactView(GeneralContextMixin, FormView):
    template_name = 'content/contact.html'

    form_class = ContactForm

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        context['is_form_valid'] = False
        return self.render_to_response(context)

    def form_valid(self, form):
        subject = 'Neue Anfrage über die Webseite: datenschutz-und-vereinsmanagement.de'
        message = ''
        for key, value in form.cleaned_data.items():
            message += '{}: {}\n'.format(key, value)
        recipient_list = ['kontakt@tortuga-webdesign.de', 'info@vereinsberatung-und-sportmanagement.de']
        email = EmailMessage(subject=subject, body=message, from_email='projekte@tortuga-webdesign.de',
                             to=recipient_list)
        email.send()
        context = {'is_form_valid': True}
        return super().render_to_response(context)


class ArticlesView(GeneralContextMixin, ListView):
    template_name = 'content/list/articles.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'tag' in self.kwargs:
            context['tag'] = Tag.objects.get(slug=self.kwargs['tag'])
        return context

    def get_queryset(self):
        articles = Article.objects.all()
        if 'tag' in self.kwargs:
            articles = articles.filter(tags__slug=self.kwargs['tag'])
        if not self.request.user.is_authenticated:
            articles = articles.exclude(is_account_required=True)
        return articles


class ArticleView(UserPassesTestMixin, GeneralContextMixin, DetailView):
    template_name = 'content/detail/article.html'
    model = Article

    def test_func(self):
        if not self.get_object().is_account_required:
            return True
        if self.request.user.is_authenticated:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = Article.objects.order_by("?")
        if not self.request.user.is_authenticated:
            articles = articles.exclude(is_account_required=True)
        articles = articles[:3]
        context['articles'] = articles
        return context


class ServiceView(GeneralContextMixin, DetailView):
    template_name = 'content/detail/service.html'
    model = Service


class AboutView(GeneralContextMixin, TemplateView):
    template_name = 'content/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['experiences'] = Experience.objects.all()
        context['educations'] = Education.objects.all()
        return context


def error_handler(request, exception=None):
    return render(request, 'content/error.html', {})


class ErrorView(GeneralContextMixin, TemplateView):
    template_name = 'content/error.html'


class DataProtectionView(GeneralContextMixin, TemplateView):
    template_name = 'content/data_protection.html'


class ImprintView(GeneralContextMixin, TemplateView):
    template_name = 'content/imprint.html'

francopioli/apps/content/templates/content/about.html
<!DOCTYPE html>

{% load lookup_tags %}
{% load martortags %}
{% load static %}
{% load svg %}

<html lang="de">

<head>
    {% include 'content/symbols/head.html' %}
</head>

<body class="font-body">

{% include 'content/symbols/auth_info.html' %}

{#{% include 'content/symbols/grid.html' %}#}

{% include 'content/symbols/navigation.html' %}

{% include 'content/symbols/subheader.html' with text=textblocks|lookup:'über-uns/abschnitt1/text' title=textblocks|lookup:'über-uns/abschnitt1/überschrift' %}

<section>
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="pt-20 pb-24">
            <div class="grid grid-cols-12 gap-4">
                <div class="col-span-12 lg:col-span-8 lg:col-start-3">
                    <h1 class="text-3xl font-futuramedium leading-tight text-center mb-24">
                        {{ textblocks|lookup:'über-uns/abschnitt2/überschrift' }}
                    </h1>
                    <h2 class="text-2xl font-futurabold mb-2">{{ textblocks|lookup:'über-uns/abschnitt2/titel' }}</h2>
                    <img class="w-1/2 mb-6" src="{% static 'img/pioli_franco.opt.jpg' %}" alt="">
                    <h3 class="text-xl font-futurabold mb-2">{{ textblocks|lookup:'über-uns/abschnitt3/titel' }}</h3>
                    <dl class="grid-cols-12 gap-1 md:gap-4 grid mb-6">
                        {% for experience in experiences %}
                            <dt class="col-span-12 md:col-span-3">
                                {{ experience.time|linebreaksbr }}
                            </dt>
                            <dd class="col-span-12 sm:col-span-9 md:col-span-8 md:col-start-5 mb-6 md:mb-0">
                                {{ experience.text|safe_markdown }}
                            </dd>
                        {% endfor %}
                    </dl>
                    <h3 class="text-xl font-futurabold mb-2">{{ textblocks|lookup:'über-uns/abschnitt4/titel' }}</h3>
                    <dl class="grid-cols-12 gap-1 md:gap-4 grid mb-6">
                        {% for education in educations %}
                            <dt class="col-span-12 md:col-span-3">
                                {{ education.time|linebreaksbr }}
                            </dt>
                            <dd class="col-span-12 sm:col-span-9 md:col-span-8 md:col-start-5 mb-6 md:mb-0">
                                {{ education.text|safe_markdown }}
                            </dd>
                        {% endfor %}
                    </dl>
                    <h3 class="text-xl font-futurabold mb-1">{{ textblocks|lookup:'über-uns/abschnitt5/titel' }}</h3>
                    <p class="mb-6">
                        {{ textblocks|lookup:'über-uns/abschnitt5/text' }}
                    </p>
                    <h3 class="text-xl font-futurabold mb-1">{{ textblocks|lookup:'über-uns/abschnitt6/titel' }}</h3>
                    <p>
                        {{ textblocks|lookup:'über-uns/abschnitt6/text' }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'content/symbols/cta.html' %}

{% include 'content/symbols/footer.html' %}

{% include 'content/symbols/scripts.html' %}

</body>

</html>

francopioli/apps/content/templates/content/index.html
<!DOCTYPE html>

{% load lookup_tags %}
{% load static %}
{% load svg %}

<html lang="de">

<head>
    {% include 'content/symbols/head.html' %}
</head>

<body class="font-body">

{% include 'content/symbols/auth_info.html' %}

{#{% include 'content/symbols/grid.html' %}#}

{% include 'content/symbols/navigation.html' %}

<section>
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="py-20">
            <div class="flex justify-center flex-wrap-reverse">
                <div class="w-full lg:w-1/2">
                    <div class="w-full lg:w-10/12 py-10">
                        <h1 class="text-4xl leading-tight font-futurabold mb-2">
                            {{ textblocks|lookup:'startseite/abschnitt1/überschrift' }}
                        </h1>
                        <p class="text-gray-800 font-body mb-10">
                            {{ textblocks|lookup:'startseite/abschnitt1/text' }}
                        </p>
                        <div class="flex items-start sm:items-center flex-wrap">
                            {% url 'content:contact' as contact_url %}
                            {% include 'content/symbols/primary-button.html' with text='Jetzt absichern' href=contact_url classes='mr-5 mb-5 sm:mb-0' %}
                            <p class="font-body">
                                Sie arbeiten bereits mit uns<br>
                                zusammen? <a class="text-green-500 hover:text-green-700" href="{% url 'users:signin' %}">Hier einloggen</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="w-full px-20 sm:px-0 sm:w-1/2">
                    <div class="w-full flex items-center">
                        {% svg 'img/dsgvo' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="bg-green-100 shadow-lg relative">
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="py-8">
            <div class="grid grid-cols-12 gap-4">
                <div class="col-span-12 md:col-span-3 mb-4 md:mb-0">
                    <div class="flex lg:h-full items-center">
                        <p class="">
                            {{ textblocks|lookup:'startseite/abschnitt2/text'|linebreaksbr }}
                        </p>
                    </div>
                </div>
                <div class="col-span-12 md:col-span-9">
                    <div class="flex justify-start sm:justify-between flex-wrap">
                        <img class="max-h-full h-20 mr-4 sm:mr-0 mb-4 lg:mb-0" src="{% static 'img/image6.png' %}"
                             alt="">
                        <img class="max-h-full h-20 mr-4 sm:mr-0 mb-4 lg:mb-0" src="{% static 'img/image2.png' %}"
                             alt="">
                        <img class="max-h-full h-20 mr-4 sm:mr-0 mb-4 lg:mb-0" src="{% static 'img/image4.png' %}"
                             alt="">
                        <img class="max-h-full h-20 mb-4 sm:mr-0 lg:mb-0" src="{% static 'img/image3.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="pt-20 pb-24">
            {% include 'content/symbols/h2.html' with text='Sie haben keinen Datenschutz?' classes='mb-10' %}
            <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
                <div class="mb-5 lg:mb-0">
                    <div class="flex mb-3 items-center lg:items-start">
                        <span class="text-4xl leading-tight w-12 mr-2 pr-2 flex-shrink-0 pt-1">
                            {% svg 'libs/@fortawesome/fontawesome-free/svgs/solid/cogs' %}
                        </span>
                        {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt3/spalte1/überschrift' %}
                    </div>
                    <p>
                        {{ textblocks|lookup:'startseite/abschnitt3/spalte1/text'|linebreaksbr }}
                    </p>
                </div>
                <div class="mb-5 lg:mb-0">
                    <div class="flex mb-3 items-center lg:items-start">
                        <span class="text-4xl leading-tight w-12 mr-2 pr-2 flex-shrink-0 pt-1">
                            {% svg 'libs/@fortawesome/fontawesome-free/svgs/solid/lock-open' %}
                        </span>
                        {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt3/spalte2/überschrift' %}
                    </div>
                    <p>
                        {{ textblocks|lookup:'startseite/abschnitt3/spalte2/text'|linebreaksbr }}
                    </p>
                </div>
                <div class="mb-5 lg:mb-0">
                    <div class="flex mb-3 items-center lg:items-start">
                        <span class="text-4xl leading-tight w-12 mr-2 pr-2 flex-shrink-0 pt-1">
                            {% svg 'libs/@fortawesome/fontawesome-free/svgs/solid/gavel' %}
                        </span>
                        {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt3/spalte3/überschrift' %}
                    </div>
                    <p>
                        {{ textblocks|lookup:'startseite/abschnitt3/spalte3/text'|linebreaksbr }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray-100">
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="pt-20 pb-24">
            {% include 'content/symbols/h2.html' with text='Bei uns bekommen Sie:' classes='mb-10' %}
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                <div class="mb-5 lg:mb-0">
                    {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt4/spalte1/überschrift' classes='mb-3' %}
                    <p>
                        {{ textblocks|lookup:'startseite/abschnitt4/spalte1/text'|linebreaksbr }}
                    </p>
                </div>
                <div class="mb-5 lg:mb-0">
                    {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt4/spalte2/überschrift' classes='mb-3' %}
                    <p>
                        {{ textblocks|lookup:'startseite/abschnitt4/spalte2/text'|linebreaksbr }}
                    </p>
                </div>
                <div class="mb-5 lg:mb-0">
                    {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt4/spalte3/überschrift' classes='mb-3' %}
                    <p>
                        {{ textblocks|lookup:'startseite/abschnitt4/spalte3/text'|linebreaksbr }}
                    </p>
                </div>
                <div class="mb-5 lg:mb-0">
                    {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt4/spalte4/überschrift' classes='mb-3' %}
                    <p>
                        {{ textblocks|lookup:'startseite/abschnitt4/spalte4/text'|linebreaksbr }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="pt-20 pb-24">
            <div class="grid grid-cols-12 gap-4">
                <div class="md:col-start-1 xl:col-start-2 md:col-span-5 col-start-2 col-span-6">
                    <img src="{% static 'img/pioli_franco.opt.jpg' %}" alt="">
                </div>
                <div class="col-span-12 md:col-span-7 lg:col-span-6 lg:col-start-7 xl:col-span-5 xl:col-start-8">
                    <div class="flex justify-center flex-col h-full">
                        {% include 'content/symbols/h2.html' with text=textblocks|lookup:'startseite/abschnitt5/überschrift' classes='mb-10' %}
                        <p class="mb-3">
                            {{ textblocks|lookup:'startseite/abschnitt5/text'|linebreaksbr }}
                        </p>
                        <ul>
                            <li>
                                <span class="mr-1 text-green-500">
                                    <i class="fas fa-check"></i>
                                </span>
                                {{ textblocks|lookup:'startseite/abschnitt5/punkt1' }}
                            </li>
                            <li>
                                <span class="mr-1 text-green-500">
                                    <i class="fas fa-check"></i>
                                </span>
                                {{ textblocks|lookup:'startseite/abschnitt5/punkt2' }}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray-100">
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="pt-20 pb-24">
            {% include 'content/symbols/h2.html' with text=textblocks|lookup:'startseite/abschnitt6/überschrift' %}
            <p class="mb-8 font-body">
                {{ textblocks|lookup:'startseite/abschnitt6/text' }}
            </p>
            <div class="flex mb-5 items-start">
                <span class="text-6xl leading-none font-futuraheavy text-green-500 w-16 flex-shrink-0 text-center">1</span>
                <div>
                    {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt6/schritt1/überschrift' classes='mb-1' %}
                    <p class="font-body">
                        {{ textblocks|lookup:'startseite/abschnitt6/schritt1/text' }}
                    </p>
                </div>
            </div>
            <div class="flex mb-5 items-start">
                <span class="text-6xl leading-none font-futuraheavy text-green-500 w-16 flex-shrink-0 text-center">2</span>
                <div>
                    {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt6/schritt2/überschrift' classes='mb-1' %}
                    <p class="font-body">
                        {{ textblocks|lookup:'startseite/abschnitt6/schritt2/text' }}
                    </p>
                </div>
            </div>
            <div class="flex items-start">
                <span class="text-6xl leading-none font-futuraheavy text-green-500 w-16 flex-shrink-0 text-center">3</span>
                <div>
                    {% include 'content/symbols/h3.html' with text=textblocks|lookup:'startseite/abschnitt6/schritt3/überschrift' classes='mb-1' %}
                    <p class="font-body">
                        {{ textblocks|lookup:'startseite/abschnitt6/schritt3/text' }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'content/symbols/cta.html' %}

{% include 'content/symbols/footer.html' %}

{% include 'content/symbols/scripts.html' %}

</body>

</html>