core/urls.py
from django.urls import path

from . import views


app_name = "content"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakt', views.ContactView.as_view(), name='contact'),
    path('artikel', views.ArticlesView.as_view(), name='articles_all'),
    # path('dsgvo', views.ArticlesView.as_view(), name='dsgvo'),
    path('artikel/tag/<slug:tag>/', views.ArticlesView.as_view(), name='articles'),
    path('artikel/<slug:slug>', views.ArticleView.as_view(), name='article'),
    path('leistung/<slug:slug>', views.ServiceView.as_view(), name='service'),
    path('ueber-uns/', views.AboutView.as_view(), name='about'),
    path('error/', views.ErrorView.as_view(), name='error'),
    path('datenschutz/', views.DataProtectionView.as_view(), name='data_protection'),
    path('impressum/', views.ImprintView.as_view(), name='imprint'),
    # user
    path('benutzer/', views.SettingsView.as_view(), name='users_index'),
    path('benutzer/login', views.SignInView.as_view(), name='signin'),
    path('benutzer/logout', views.SignOutView.as_view(), name='signout'),
    path('benutzer/einstellungen', views.SettingsView.as_view(), name='settings'),
    path('benutzer/passwort-aendern', views.CustomPasswordChangeView.as_view(), name='password_change'),
]

francopioli/apps/content/urls.py
from django.urls import path

from . import views


app_name = "content"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('kontakt', views.ContactView.as_view(), name='contact'),
    path('artikel', views.ArticlesView.as_view(), name='articles'),
    path('artikel/tag/<slug:tag>/', views.ArticlesView.as_view(), name='articles_tag'),
    path('artikel/<slug:slug>', views.ArticleView.as_view(), name='article'),
    path('leistung/<slug:slug>', views.ServiceView.as_view(), name='service'),
    path('ueber-uns/', views.AboutView.as_view(), name='about'),
    path('error/', views.ErrorView.as_view(), name='error'),
    path('datenschutz/', views.DataProtectionView.as_view(), name='data_protection'),
    path('impressum/', views.ImprintView.as_view(), name='imprint'),
]

core/models/users.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

core/forms.py
from django import forms


class ContactForm(forms.Form):
    vorname = forms.CharField()
    nachname = forms.CharField()
    email = forms.EmailField()
    nachricht = forms.CharField()

    def clean_nachricht(self):
        message = self.cleaned_data['nachricht']
        if 'http://' in message or 'https://' in message or 'usd' in message.lower():
            raise forms.ValidationError('In der Nachricht sind keine Links erlaubt.')
        return message

francopioli/apps/content/forms.py
from django import forms

from .models import Article

from martor.widgets import AdminMartorWidget


class ArticleForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d"),
                           input_formats=["%Y-%m-%d"], label="Date")
    content = forms.CharField(widget=AdminMartorWidget)

    class Meta:
        model = Article
        fields = '__all__'


class ContactForm(forms.Form):
    vorname = forms.CharField()
    nachname = forms.CharField()
    email = forms.EmailField()
    nachricht = forms.CharField()

    def clean_nachricht(self):
        message = self.cleaned_data['nachricht']
        if 'http://' in message or 'https://' in message or 'usd' in message.lower():
            raise forms.ValidationError('In der Nachricht sind keine Links erlaubt.')
        return message

core/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import FormView
from django.core.mail import EmailMessage
from django.shortcuts import render
from .models import Experience
from .models import Education
from .models import Article
from .models import Service
from .models import Tag
from .forms import ContactForm


from django.views.generic.base import ContextMixin
from .models import TextBlock
from .models import Code
from .models import Seo

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from django.urls import reverse_lazy


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'password.html'
    success_url = reverse_lazy('content:signin')


class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    pass


class SignInView(LoginView):
    template_name = 'login.html'
    redirect_field_name = 'next'


class SettingsView(LoginRequiredMixin, TemplateView):
    template_name = 'settings.html'


class SignOutView(LogoutView):
    next_page = '/'


class WebsiteContextMixin(ContextMixin):
    def get_seo_data(self):
        seos = []
        for seo in Seo.objects.all():
            if seo.url in self.request.get_full_path():
                seos.append(seo)

        if not seos:
            seo = Seo.objects.filter(url='').first()
            if seo:
                return {'title': seo.title_tag, 'description': seo.meta_description}
            else:
                return {'title': 'No title yet.', 'description': 'No description yet.'}

        final_seo = None
        slug_length = -1
        for seo in seos:
            seo_slug_length = len(seo.url)
            if seo_slug_length > slug_length:
                final_seo = seo
                slug_length = seo_slug_length

        return {'title': final_seo.title_tag, 'description': final_seo.meta_description}

    def get_custom_code(self):
        header_code = ''
        footer_code = ''
        custom_codes = []
        for custom_code in Code.objects.all():
            cc_slug = custom_code.url
            if cc_slug == '' or cc_slug in self.request.get_full_path():
                custom_codes.append(custom_code)
        for custom_code in custom_codes:
            if custom_code.location == 'HEAD':
                header_code += custom_code.code
            else:
                footer_code += custom_code.code
        return {'header_code': header_code, 'footer_code': footer_code}

    def get_text_blocks(self):
        data = {}
        for text_block in list(TextBlock.objects.all()):
            data[text_block.key] = text_block.content
        return {'textblocks': data}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_seo_data())
        context.update(self.get_custom_code())
        context.update(self.get_text_blocks())
        return context


class GeneralContextMixin(WebsiteContextMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        context['textblocks'] = TextBlock.get_dict()
        return context


class IndexView(GeneralContextMixin, TemplateView):
    template_name = 'content/index.html'


class ContactView(GeneralContextMixin, FormView):
    template_name = 'content/contact.html'

    form_class = ContactForm

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        context['is_form_valid'] = False
        return self.render_to_response(context)

    def form_valid(self, form):
        subject = 'Neue Anfrage über die Webseite: datenschutz-und-vereinsmanagement.de'
        message = ''
        for key, value in form.cleaned_data.items():
            message += '{}: {}\n'.format(key, value)
        recipient_list = ['kontakt@tortuga-webdesign.de', 'info@vereinsberatung-und-sportmanagement.de']
        email = EmailMessage(subject=subject, body=message, from_email='projekte@tortuga-webdesign.de',
                             to=recipient_list)
        email.send()
        context = {'is_form_valid': True}
        return super().render_to_response(context)


class ArticlesView(GeneralContextMixin, ListView):
    template_name = 'content/list/articles.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'tag' in self.kwargs:
            context['tag'] = Tag.objects.get(slug=self.kwargs['tag'])
        return context

    def get_queryset(self):
        articles = Article.objects.all()
        if 'tag' in self.kwargs:
            articles = articles.filter(tags__slug=self.kwargs['tag'])
        if not self.request.user.is_authenticated:
            articles = articles.exclude(is_account_required=True)
        return articles


class ArticleView(UserPassesTestMixin, GeneralContextMixin, DetailView):
    template_name = 'content/detail/article.html'
    model = Article

    def test_func(self):
        if not self.get_object().is_account_required:
            return True
        if self.request.user.is_authenticated:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = Article.objects.order_by("?")
        if not self.request.user.is_authenticated:
            articles = articles.exclude(is_account_required=True)
        articles = articles[:3]
        context['articles'] = articles
        return context


class ServiceView(GeneralContextMixin, DetailView):
    template_name = 'content/detail/service.html'
    model = Service


class AboutView(GeneralContextMixin, TemplateView):
    template_name = 'content/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['experiences'] = Experience.objects.all()
        context['educations'] = Education.objects.all()
        return context


def error_handler(request, exception=None):
    return render(request, 'content/error.html', {})


class ErrorView(GeneralContextMixin, TemplateView):
    template_name = 'content/error.html'


class DataProtectionView(GeneralContextMixin, TemplateView):
    template_name = 'content/data_protection.html'


class ImprintView(GeneralContextMixin, TemplateView):
    template_name = 'content/imprint.html'

francopioli/apps/content/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import TemplateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import FormView
from django.core.mail import EmailMessage
from django.shortcuts import render

from apps.core.models import TextBlock
from apps.core.views import WebsiteContextMixin
from .models import Experience
from .models import Education
from .models import Article
from .models import Service
from .models import Tag
from .forms import ContactForm


class GeneralContextMixin(WebsiteContextMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        context['textblocks'] = TextBlock.get_dict()
        return context


class IndexView(GeneralContextMixin, TemplateView):
    template_name = 'content/index.html'


class ContactView(GeneralContextMixin, FormView):
    template_name = 'content/contact.html'

    form_class = ContactForm

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        context['is_form_valid'] = False
        return self.render_to_response(context)

    def form_valid(self, form):
        subject = 'Neue Anfrage über die Webseite: datenschutz-und-vereinsmanagement.de'
        message = ''
        for key, value in form.cleaned_data.items():
            message += '{}: {}\n'.format(key, value)
        recipient_list = ['kontakt@tortuga-webdesign.de', 'info@vereinsberatung-und-sportmanagement.de']
        email = EmailMessage(subject=subject, body=message, from_email='projekte@tortuga-webdesign.de',
                             to=recipient_list)
        email.send()
        context = {'is_form_valid': True}
        return super().render_to_response(context)


class ArticlesView(GeneralContextMixin, ListView):
    template_name = 'content/list/articles.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'tag' in self.kwargs:
            context['tag'] = Tag.objects.get(slug=self.kwargs['tag'])
        return context

    def get_queryset(self):
        articles = Article.objects.all()
        if 'tag' in self.kwargs:
            articles = articles.filter(tags__slug=self.kwargs['tag'])
        if not self.request.user.is_authenticated:
            articles = articles.exclude(is_account_required=True)
        return articles


class ArticleView(UserPassesTestMixin, GeneralContextMixin, DetailView):
    template_name = 'content/detail/article.html'
    model = Article

    def test_func(self):
        if not self.get_object().is_account_required:
            return True
        if self.request.user.is_authenticated:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = Article.objects.order_by("?")
        if not self.request.user.is_authenticated:
            articles = articles.exclude(is_account_required=True)
        articles = articles[:3]
        context['articles'] = articles
        return context


class ServiceView(GeneralContextMixin, DetailView):
    template_name = 'content/detail/service.html'
    model = Service


class AboutView(GeneralContextMixin, TemplateView):
    template_name = 'content/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['experiences'] = Experience.objects.all()
        context['educations'] = Education.objects.all()
        return context


def error_handler(request, exception=None):
    return render(request, 'content/error.html', {})


class ErrorView(GeneralContextMixin, TemplateView):
    template_name = 'content/error.html'


class DataProtectionView(GeneralContextMixin, TemplateView):
    template_name = 'content/data_protection.html'


class ImprintView(GeneralContextMixin, TemplateView):
    template_name = 'content/imprint.html'

francopioli/apps/core/views.py
from django.views.generic.base import ContextMixin
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect

from .models import TextBlock
from .models import Code
from .models import Seo

import re


class WebsiteContextMixin(ContextMixin):
    def get_seo_data(self):
        seos = []
        for seo in Seo.objects.all():
            if seo.url in self.request.get_full_path():
                seos.append(seo)

        if not seos:
            seo = Seo.objects.filter(url='').first()
            if seo:
                return {'title': seo.title_tag, 'description': seo.meta_description}
            else:
                return {'title': 'No title yet.', 'description': 'No description yet.'}

        final_seo = None
        slug_length = -1
        for seo in seos:
            seo_slug_length = len(seo.url)
            if seo_slug_length > slug_length:
                final_seo = seo
                slug_length = seo_slug_length

        return {'title': final_seo.title_tag, 'description': final_seo.meta_description}

    def get_custom_code(self):
        header_code = ''
        footer_code = ''
        custom_codes = []
        for custom_code in Code.objects.all():
            cc_slug = custom_code.url
            if cc_slug == '' or cc_slug in self.request.get_full_path():
                custom_codes.append(custom_code)
        for custom_code in custom_codes:
            if custom_code.location == 'HEAD':
                header_code += custom_code.code
            else:
                footer_code += custom_code.code
        return {'header_code': header_code, 'footer_code': footer_code}

    def get_text_blocks(self):
        data = {}
        for text_block in list(TextBlock.objects.all()):
            data[text_block.key] = text_block.content
        return {'textblocks': data}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_seo_data())
        context.update(self.get_custom_code())
        context.update(self.get_text_blocks())
        return context


class StaticRedirectView(RedirectView):
    def get(self, request, *args, **kwargs):
        current_url = self.request.get_full_path()
        splitted_url = re.split(r'(js|images|css)', current_url)
        url = ''.join(splitted_url[1:])
        static_url = '/static/' + url
        return HttpResponseRedirect(static_url)


class AnyHtmlView(WebsiteContextMixin, TemplateView):
    def get(self, *args, **kwargs):
        current_url = self.request.get_full_path()
        current_url = current_url.strip('/')
        self.template_name = current_url
        return super().get(self, *args, **kwargs)

core/templates/content/symbols/article_card.html
{% load static %}

<div class="rounded overflow-hidden shadow-lg flex flex-col bg-white border {{ classes }}">
    <a href="{% url 'content:article' slug %}"><img class="w-full" src="{{ image }}" alt="{{ title }}"></a>
    <div class="flex justify-between flex-col h-full">
        <div class="px-6 pt-4 pb-5">
            <a href="{% url 'content:article' slug %}">
                <div class="font-bold text-xl mb-2">{{ title }}</div>
            </a>
            <p class="text-gray-700 text-base">
                {{ description }}
            </p>
        </div>
        {#        <div class="px-6 py-4 pt-3 flex flex-wrap">#}
        {#            {% for tag in tags %}#}
        {#                <a class="mr-1 mt-1" href="{% url 'content:articles_tag' tag.slug %}"><span#}
        {#                        class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">#{{ tag }}</span></a>#}
        {#            {% endfor %}#}
        {#        </div>#}
    </div>
</div>

core/templates/content/symbols/articles_breadcrumbs.html
<nav class="text-black my-4" aria-label="Breadcrumb">
    <ol class="list-none p-0 inline-flex">
        <li class="flex items-center">
            {% url 'content:articles_all' as articles_url %}
            {% include 'content/symbols/link.html' with text='Artikel' href=articles_url %}
            {% if tag or article %}
                <svg class="fill-current w-3 h-3 mx-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
                    <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"/>
                </svg>
            {% endif %}
        </li>
        {% if tag %}
            <li class="flex items-center">
                {% url 'content:articles' tag.slug as tag_url %}
                {% include 'content/symbols/link.html' with text=tag.name href=tag_url %}
                {#                <span class="text-gray-600">{{ tag.name }}</span>#}
            </li>
        {% elif article %}
            <li class="flex items-center">
                {% url 'content:articles' article.tags.first.slug as tag_url %}
                {% include 'content/symbols/link.html' with text=article.tags.first.name href=tag_url %}
                <svg class="fill-current w-3 h-3 mx-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
                    <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"/>
                </svg>
            </li>
            <li class="flex items-center">
                <span class="text-gray-600">{{ article.title }}</span>
            </li>
        {% else %}
            {#            <li class="flex items-center">#}
            {#                <span class="text-gray-600">Alle</span>#}
            {#            </li>#}
        {% endif %}
    </ol>
</nav>

core/templates/content/symbols/cta.html
{% load lookup_tags %}

<section class="bg-green-100 shadow-lg relative">
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="py-8">
            <div class="flex justify-between items-center lg:h-20">
                <h2 class="text-3xl font-futurabold">{{ textblocks|lookup:'call-to-action/text' }}</h2>
                {% url 'content:contact' as contact_url %}
                {% include 'content/symbols/primary-button.html' with text='Jetzt absichern' href=contact_url classes='flex-shrink-0' %}
            </div>
        </div>
    </div>
</section>

core/templates/content/symbols/footer.html
{% load lookup_tags %}
{% load svg %}

<section class="bg-gray-100">
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="pt-20 pb-24">
            <div class="grid grid-cols-12 gap-4">
                <div class="col-span-12 lg:col-span-6 mb-10 lg:mb-0">
                    <div class="w-64 mb-8">
                        {% svg 'img/francopiolilogo' %}
                    </div>
                    <p class="text-2xl leading-tight">
                        {{ textblocks|lookup:'footer/text'|linebreaksbr }}
                    </p>
                </div>
                <div class="col-span-12 sm:col-span-6 lg:col-span-2 mb-10 sm:mb-0">
                    <h2 class="text-2xl leading-tight font-futuraheavy mb-5">Navigation</h2>
                    <ul>
                        {% url 'content:index' as index_url %}
                        <li class="text-lg">{% include 'content/symbols/link.html' with text='Startseite' href=index_url %}</li>
                        {% url 'content:articles' as articles_url %}
                        <li class="text-lg">{% include 'content/symbols/link.html' with text='Artikel' href=articles_url %}</li>
                        {% url 'content:about' as about_url %}
                        <li class="text-lg">{% include 'content/symbols/link.html' with text='Über uns' href=about_url %}</li>
                        {% url 'content:contact' as contact_url %}
                        <li class="text-lg">{% include 'content/symbols/link.html' with text='Kontakt' href=contact_url %}</li>
                    </ul>
                </div>
                <div class="col-span-12 sm:col-span-6 lg:col-span-4">
                    <div class="flex flex-col sm:items-end sm:text-right">
                        <h2 class="text-2xl leading-tight font-futuraheavy mb-5">Kontakt</h2>
                        <p class="mb-1">
                            Franco Pioli <br>
                            Ahornstraße 6 <br>
                            85457 Wörth
                        </p>
                        <p>
                            Mobil: {% include 'content/symbols/link.html' with text='0179 1408990' href='#' %} <br>
                            Mail: {% include 'content/symbols/link.html' with text='info@vereinsberatung-und-sportmanagement.de' href='#' %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="">
        <div class="container px-4 sm:px-2 mx-auto">
            <div class="py-4">
                <div class="flex justify-between text-gray-600 flex-wrap">
                    <p class="mb-2 sm:mb-1">
                        <span class="">© 2020 Franco Pioli</span>&nbsp;&nbsp;&nbsp;<a class="hover:text-gray-800" href="{% url 'content:imprint' %}">Impressum</a>&nbsp;&nbsp;&nbsp;<a class="hover:text-gray-800" href="{% url 'content:data_protection' %}">Datenschutz</a>
                    </p>
                    <p class="sr-only">
                        Seite erstellt von <a class="hover:text-gray-800" href="https://tortuga-webdesign.de" target="_blank">Daniel Mössner</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

core/templates/content/symbols/grid.html
<section class="fixed top-0 h-screen w-full" style="z-index: -1">
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="grid gap-4 grid-cols-12">
            <div class="bg-gray-200 opacity-50 h-screen"></div>
            <div class="bg-gray-200 opacity-50"></div>
            <div class="bg-gray-200 opacity-50"></div>
            <div class="bg-gray-200 opacity-50"></div>

            <div class="bg-gray-200 opacity-50"></div>
            <div class="bg-gray-200 opacity-50"></div>
            <div class="bg-gray-200 opacity-50"></div>
            <div class="bg-gray-200 opacity-50"></div>

            <div class="bg-gray-200 opacity-50"></div>
            <div class="bg-gray-200 opacity-50"></div>
            <div class="bg-gray-200 opacity-50"></div>
            <div class="bg-gray-200 opacity-50"></div>
        </div>
    </div>
</section>

core/templates/content/symbols/navigation.html
{% load svg %}
<nav class="bg-white border-b-2 border-gray-200 shadow">
    <div class="container px-4 sm:px-2 mx-auto">
        <div class="flex items-center justify-between flex-wrap py-3">
            <a href="{% url 'content:index' %}" class="block flex items-center w-3/5 sm:w-2/5 md:w-1/5 md:-ml-4">
                {% svg 'img/francopiolilogo' %}
            </a>
            <div class="block lg:hidden">
                <button class="flex items-center px-3 py-2 border rounded focus text-green-500 border-green-500 hover:text-gray-800 hover:border-gray-800"
                        id="burger">
                    <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>
                        Menü</title>
                        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
                    </svg>
                </button>
            </div>
            <div class="w-full hidden lg:block flex-grow lg:flex lg:items-center lg:w-auto font-body" id="burger-ziel">
                <div class="text-base lg:flex-grow text-left lg:text-right">
                    <a href="{% url 'content:index' %}"
                       class="block mt-4 lg:mt-0 lg:inline-block lg:mt-0 text-gray-800 hover:text-black lg:mr-4 border-2 p-1 rounded border-transparent hover:border-gray-300">
                        Startseite
                    </a>
                    <a href="{% url 'content:about' %}"
                       class="block mt-4 lg:mt-0 lg:inline-block lg:mt-0 text-gray-800 hover:text-black lg:mr-4 border-2 p-1 rounded border-transparent hover:border-gray-300">
                        Über uns
                    </a>
                    <a href="{% url 'content:articles' 'dsgvo' %}"
                       class="block mt-1 lg:mt-0 lg:inline-block lg:mt-0 text-gray-800 hover:text-black lg:mr-4 border-2 p-1 rounded border-transparent hover:border-gray-300">
                        Datenschutz / DSGVO
                    </a>
                    <a href="{% url 'content:articles' 'vereinsmanagement' %}"
                       class="block mt-1 lg:mt-0 lg:inline-block lg:mt-0 text-gray-800 hover:text-black lg:mr-4 border-2 p-1 rounded border-transparent hover:border-gray-300">
                        Vereinsmanagement
                    </a>
                    <div class="relative inline-block w-full lg:w-auto">
                        <a class="block mt-1 lg:mt-0 lg:inline-block lg:mt-0 text-gray-800 hover:text-black lg:mr-4 border-2 p-1 rounded border-transparent hover:border-gray-300"
                           href="#" id="weitere-leistungen">
                            Unsere Leistungen
                            <div class="inline-block transform rotate-90" id="weitere-leistungen-dreieck">
                                <svg class="fill-current w-3 h-3" xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 320 512">
                                    <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"/>
                                </svg>
                            </div>

                        </a>
                        <div class="w-full rounded hidden absolute top-0 bg-white border-b-2 border-gray-200 transform translate-y-12 text-left shadow"
                             id="weitere-leistungen-ziel">
                            {% for service in services %}
                                <a href="{% url 'content:service' service.slug %}"
                                   class="block m-2 p-1 text-gray-800 text-gray-800 hover:text-black border-2 rounded border-transparent hover:border-gray-300">
                                    {{ service.name }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                    <a href="{% url 'content:contact' %}"
                       class="block lg:inline-block lg:mt-0 text-gray-800 hover:text-black lg:mr-4 border-2 p-1 rounded border-transparent hover:border-gray-300">
                        Kontakt
                    </a>
                </div>
                <a href="{% url 'content:contact' %}"
                   class="text-base px-4 py-2 lg:inline-block hidden rounded bg-green-500 leading-none border text-white border-green-500 border-2 hover:bg-green-600 font-futuramedium">Jetzt
                    absichern</a>
            </div>
        </div>
    </div>
</nav>